// src/views/Library.vue
<template>
  <div class="pa-6">
    <div class="library-header d-flex align-center gap-4 mb-6">
      <h2 class="text-h5 library-header__title">
        <template v-if="collectionsStore.isAllActive">{{ t('nav.library') }}</template>
        <template v-else>"{{ collectionsStore.activeCollectionName }}"</template>
      </h2>
      <span class="spacer" />

      <SearchBox
        v-model="libraryStore.query"
        :placeholder="t('lib.search.placeholder')"
        :clear-label="t('common.clear')"
        @commit="libraryStore.applySearch"
      />

      <md-filled-button @click="onImport">
        <MdiIcon slot="icon" :path="mdiFolderOpen" :size="20" />
        {{ t('lib.import') }}
      </md-filled-button>

      <md-circular-progress v-if="libraryStore.isLoading" indeterminate />
    </div>

    <div v-if="libraryStore.allTags.length" class="tag-chips mb-6">
      <button
        v-for="tag in libraryStore.allTags"
        :key="tag.name"
        class="tag-chip"
        :class="{ 'tag-chip--selected': libraryStore.selectedTags.includes(tag.name) }"
        :aria-pressed="libraryStore.selectedTags.includes(tag.name)"
        @click="libraryStore.toggleTag(tag.name)"
      >
        <span class="tag-chip__label">{{ tag.name }}</span>
        <span class="tag-chip__count">({{ tag.count }})</span>
      </button>
      <!-- The chip row is capped (backend returns the top 30 tags). When that
           cap is reached, show a non-interactive "…" chip to signal more tags
           exist — they're reachable via the search box, which also matches tag
           names now. -->
      <span
        v-if="libraryStore.allTags.length >= TAG_DISPLAY_LIMIT"
        class="tag-chip tag-chip--ellipsis"
        aria-hidden="true"
      >…</span>
    </div>

    <div
      v-if="libraryStore.books.length"
      class="md3-grid"
    >
      <div v-for="book in libraryStore.books" :key="book.id">
        <SourceCard
          :id="'book-anchor-' + book.id"
          :title="book.title"
          :page-count="book.page_count"
          :subtitle="book.author"
          :cover="coverMap[book.id] ?? null"
          @click="router.push(`/reader/${book.id}`)"
          @contextmenu.prevent="openMenu(book.id)"
        />

        <md-menu
          :id="'book-menu-' + book.id"
          :ref="(el: unknown) => setMenuRef(book.id, el as MdMenuElement | null)"
          :anchor="'book-anchor-' + book.id"
          :open="menuOpen[book.id]"
          positioning="fixed"
          @closed="menuOpen[book.id] = false"
        >
          <md-menu-item @click="openCollectionPicker(book.id)">
            <MdiIcon slot="start" :path="mdiPlaylistPlus" :size="18" />
            <div slot="headline">{{ t('lib.collections.addTo') }}</div>
          </md-menu-item>
          <md-menu-item @click="viewMeta(book)">
            <MdiIcon slot="start" :path="mdiInformationOutline" :size="18" />
            <div slot="headline">{{ t('lib.viewMeta') }}</div>
          </md-menu-item>
          <md-menu-item @click="saveToLocal(book)">
            <MdiIcon slot="start" :path="mdiContentSave" :size="18" />
            <div slot="headline">{{ t('lib.save') }}</div>
          </md-menu-item>
          <md-menu-item @click="deleteBookItem(book)">
            <MdiIcon slot="start" :path="mdiDelete" :size="18" />
            <div slot="headline">{{ t('lib.delete') }}</div>
          </md-menu-item>
        </md-menu>
      </div>
    </div>

    <div v-if="libraryStore.books.length" class="feed-sentinel-wrap">
      <!-- Infinite-scroll sentinel: intersecting triggers loadMore(); the store
           no-ops while a load is in flight or the filter is exhausted. -->
      <div ref="sentinelEl" class="feed-sentinel" />
      <div v-if="libraryStore.isLoadingMore" class="feed-loading">
        <md-circular-progress indeterminate />
      </div>
    </div>

    <div
      v-if="!libraryStore.books.length && !libraryStore.isLoading"
      class="text-center text-medium-emphasis mt-8"
    >
      {{ t('lib.empty') }}
    </div>

    <!-- Shared meta dialog -->
    <BookMetaDialog ref="metaDialog" />

    <!-- Shared export dialog (format picker → save) -->
    <BookExportDialog ref="exportDialog" />

    <!-- Collection management FAB + dialogs -->
    <FabButton
      :icon="mdiPlaylistPlay"
      :aria-label="t('lib.collections.manage')"
      @click="showCollectionDialog = true"
    />

    <CollectionDialog
      :model-value="showCollectionDialog"
      @update:model-value="showCollectionDialog = $event"
      @close="showCollectionDialog = false"
    />

    <BookCollectionPicker
      v-if="pickerBookId"
      :book-id="pickerBookId"
      @close="pickerBookId = null"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, reactive } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import '@material/web/menu/menu.js';
import '@material/web/menu/menu-item.js';
import {
  mdiFolderOpen,
  mdiContentSave,
  mdiDelete,
  mdiInformationOutline,
  mdiPlaylistPlay,
  mdiPlaylistPlus,
} from '@mdi/js';
import { useLibraryStore } from '@/stores/library';
import { useCollectionsStore } from '@/stores/collections';
import { api } from '@/services/api';
import { getThumb, setThumb, deleteThumb } from '@/services/thumb-cache';
import { useToastStore } from '@/stores/toast';
import { useI18n } from '@/i18n';
import MdiIcon from '@/components/MdiIcon.vue';
import SourceCard from '@/components/SourceCard.vue';
import SearchBox from '@/components/SearchBox.vue';
import FabButton from '@/components/FabButton.vue';
import CollectionDialog from '@/components/CollectionDialog.vue';
import BookCollectionPicker from '@/components/BookCollectionPicker.vue';
import BookMetaDialog from '@/components/BookMetaDialog.vue';
import BookExportDialog from '@/components/BookExportDialog.vue';
import { useInfiniteSentinel } from '@/composables/useInfiniteSentinel';
import { useBookMenu, type MdMenuElement } from '@/composables/useBookMenu';
import type { Book } from '@/types';

const router = useRouter();
const route = useRoute();
const libraryStore = useLibraryStore();
const collectionsStore = useCollectionsStore();
const toast = useToastStore();
const { t } = useI18n();

const { menuOpen, menuRefs, pickerBookId, setMenuRef, openMenu, openCollectionPicker, cleanupBook, clearAll } = useBookMenu();
const metaDialog = ref<InstanceType<typeof BookMetaDialog> | null>(null);
const exportDialog = ref<InstanceType<typeof BookExportDialog> | null>(null);

/** Infinite-scroll sentinel — IntersectionObserver calls loadMore() when the
 *  grid bottom scrolls near (the store no-ops while busy or exhausted).
 *  feedState lets the sentinel auto-fill: after each page load finishes, it
 *  rechecks whether the grid has filled the viewport. */
const sentinelEl = ref<HTMLElement | null>(null);
useInfiniteSentinel(sentinelEl, () => libraryStore.loadMore(), {
  feedState: {
    get loading() { return libraryStore.isLoading || libraryStore.isLoadingMore; },
    get end() { return !libraryStore.hasMore; },
  },
});

const coverMap = reactive<Record<string, string | null>>({});
const showCollectionDialog = ref(false);

/** Chip-row display cap (backend `get_all_tags` returns the top 30). When the
 *  cap is reached we append a non-interactive "…" chip to signal more exist. */
const TAG_DISPLAY_LIMIT = 30;

let prevIds = new Set<string>();

async function loadCover(book: Book) {
  if (book.id in coverMap) return;
  coverMap[book.id] = null;
  let alive = true;
  let made: string | null = null;
  try {
    // Try the IndexedDB thumbnail cache first. Key by source_post_id (Pixiv
    // illust id / EHentai gid) so the SAME cover is shared with the browse
    // pages — a cover cached while browsing is reused for the downloaded book
    // and vice versa. Local imports (no source_post_id) fall back to book id.
    const cacheKey = book.source_post_id || book.id;
    let blob = await getThumb(cacheKey);
    if (!blob) {
      const bytes = await api.getBookCoverThumb(book.id);
      if (!alive) return;
      blob = new Blob([new Uint8Array(bytes)], { type: 'image/jpeg' });
      void setThumb(cacheKey, blob);
    }
    if (!alive) return;
    made = URL.createObjectURL(blob);
    coverMap[book.id] = made;
  } catch {
    // leave placeholder
  }
  return () => {
    alive = false;
    if (made) URL.revokeObjectURL(made);
  };
}

const stopCoverWatch = watch(
  () => libraryStore.books,
  (books) => {
    const currentIds = new Set(books.map((b) => b.id));
    for (const id of prevIds) {
      if (!currentIds.has(id)) {
        const url = coverMap[id];
        if (url) URL.revokeObjectURL(url);
        delete coverMap[id];
        cleanupBook(id);
      }
    }
    prevIds = currentIds;
    for (const book of books) loadCover(book);
  },
  { immediate: true },
);

onMounted(() => {
  libraryStore.ensureLoaded();
  collectionsStore.ensureLoaded();
});

// When the active collection changes, re-filter the library and re-tally tags.
const stopCollectionWatch = watch(
  () => collectionsStore.activeCollectionId,
  () => {
    libraryStore.collectionFilter = collectionsStore.activeCollectionName;
    // reload() fetches books, but we also need tag counts scoped to the
    // collection. applySearch() calls loadTags() with the current text filter.
    libraryStore.applySearch();
  },
);

// When navigated to (e.g. from Tasks "view" button) with ?search=…,
// set the text box and trigger a search. Also sync the collection filter
// so the switch to "All" (done by Tasks before navigating) takes effect.
const stopRouteWatch = watch(
  () => route.query.search,
  (val) => {
    const text = (typeof val === 'string' && val) ? val : '';
    if (!text) return;
    // Always sync collectionFilter to the current store state first, so a
    // prior setActiveCollection(null) from another view takes effect.
    libraryStore.collectionFilter = collectionsStore.activeCollectionName;
    if (text === libraryStore.query) {
      // Same query text but collection may have changed — still reload.
      libraryStore.applySearch();
      return;
    }
    libraryStore.query = text;
    libraryStore.applySearch();
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  stopCoverWatch();
  stopRouteWatch();
  stopCollectionWatch();
  for (const url of Object.values(coverMap)) {
    if (url) URL.revokeObjectURL(url);
  }
  clearAll();
});

async function onImport() {
  const file = await api.openFile([
    { name: t('lib.import.filterName'), extensions: ['cb7', 'cbz', 'cbr', 'epub', 'pdf'] },
  ]);
  if (typeof file === 'string') {
    try {
      const book = await api.importBook(file);
      await libraryStore.refresh();
      toast.addToast('success', t('lib.imported', { title: book.title }));
    } catch (e) {
      toast.addToast('error', t('lib.importFailed', { error: String(e) }));
    }
  }
}

async function deleteBookItem(book: Book) {
  menuOpen[book.id] = false;
  try {
    await libraryStore.deleteBook(book.id);
    void deleteThumb(book.id);
    toast.addToast('success', t('lib.deleted', { title: book.title }));
  } catch (e) {
    toast.addToast('error', t('lib.deleteFailed', { error: String(e) }));
  }
}

async function saveToLocal(book: Book) {
  menuOpen[book.id] = false;
  exportDialog.value?.open(book);
}

function viewMeta(book: Book) {
  menuOpen[book.id] = false;
  metaDialog.value?.open(book);
}
</script>

<style scoped>
.library-header__title {
  margin: 0;
  white-space: nowrap;
}

.tag-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.tag-chip {
  display: inline-flex;
  align-items: center;
  gap: 3px;
  height: 26px;
  padding: 0 10px;
  border: 1px solid var(--md-sys-color-outline);
  border-radius: var(--md-sys-shape-corner-full);
  background: transparent;
  color: var(--md-sys-color-on-surface-variant);
  font-size: 12px;
  line-height: 1;
  cursor: pointer;
  transition:
    background-color 0.15s ease,
    color 0.15s ease,
    border-color 0.15s ease;
}

.tag-chip:hover {
  background: color-mix(in srgb, var(--md-sys-color-on-surface) 8%, transparent);
}

.tag-chip--selected {
  background: var(--md-sys-color-secondary-container);
  border-color: transparent;
  color: var(--md-sys-color-on-secondary-container);
}

.tag-chip--selected:hover {
  background: color-mix(
    in srgb,
    var(--md-sys-color-on-secondary-container) 12%,
    var(--md-sys-color-secondary-container)
  );
}

.tag-chip__count {
  font-size: 11px;
  opacity: 0.75;
}

.tag-chip--ellipsis {
  border: none;
  background: transparent;
  color: var(--md-sys-color-on-surface-variant);
  cursor: default;
  opacity: 0.6;
}

.feed-sentinel {
  height: 1px;
  width: 100%;
}

.feed-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px 0;
}
</style>

// src/views/Library.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '@/services/api';
import { getThumb, setThumb, deleteThumb } from '@/services/thumb-cache';
import { useI18n } from '@/hooks/useI18n';
import { useLibraryStore } from '@/stores/library';
import { useCollectionsStore } from '@/stores/collections';
import { useToastStore } from '@/stores/toast';
import { useBookMenu } from '@/hooks/useBookMenu';
import { useInfiniteSentinel } from '@/hooks/useInfiniteSentinel';
import { MdiIcon } from '@/components/MdiIcon';
import { SourceCard } from '@/components/SourceCard';
import { SearchBox } from '@/components/SearchBox';
import { FabButton } from '@/components/FabButton';
import { BookMenu } from '@/components/BookMenu';
import {
  mdiContentSave,
  mdiDelete,
  mdiFolderOpen,
  mdiInformationOutline,
  mdiPlaylistPlay,
  mdiPlaylistPlus,
} from '@mdi/js';
import { BookMetaDialog, type BookMetaDialogHandle } from '@/components/BookMetaDialog';
import { BookExportDialog, type BookExportDialogHandle } from '@/components/BookExportDialog';
import { BookCollectionPicker } from '@/components/BookCollectionPicker';
import { CollectionDialog } from '@/components/CollectionDialog';
import type { Book } from '@/types';

const TAG_DISPLAY_LIMIT = 30;

export default function Library() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { t } = useI18n();
  const libraryStore = useLibraryStore();
  const collectionsStore = useCollectionsStore();
  const toast = useToastStore();
  const { openBookId, pickerBookId, openMenu, closeMenu, openCollectionPicker } = useBookMenu();
  const metaDialogRef = useRef<BookMetaDialogHandle>(null);
  const exportDialogRef = useRef<BookExportDialogHandle>(null);
  const [coverMap, setCoverMap] = useState<Record<string, string | null>>({});
  const coverMapRef = useRef(coverMap);
  coverMapRef.current = coverMap;
  const [showCollectionDialog, setShowCollectionDialog] = useState(false);
  const pendingCovers = useRef(new Set<string>());
  const title = collectionsStore.isAllActive ? t('nav.library') : `"${collectionsStore.activeCollectionName}"`;

  const sentinelRef = useInfiniteSentinel(() => libraryStore.loadMore(), {
    feedState: { loading: libraryStore.isLoading || libraryStore.isLoadingMore, end: !libraryStore.hasMore },
  });

  async function loadCover(book: Book) {
    if (book.id in coverMap || pendingCovers.current.has(book.id)) return;
    pendingCovers.current.add(book.id);
    setCoverMap((prev) => ({ ...prev, [book.id]: null }));
    try {
      const cacheKey = book.source_post_id || book.id;
      let blob = await getThumb(cacheKey);
      if (!blob) { const bytes = await api.getBookCoverThumb(book.id); blob = new Blob([new Uint8Array(bytes)], { type: 'image/jpeg' }); void setThumb(cacheKey, blob); }
      const made = URL.createObjectURL(blob);
      setCoverMap((prev) => ({ ...prev, [book.id]: made }));
    } catch { /* leave placeholder */ }
    finally { pendingCovers.current.delete(book.id); }
  }

  // Revoke covers for books that left the grid, load covers for new ones.
  const prevIds = useRef<Set<string>>(new Set());
  useEffect(() => {
    const currentIds = new Set(libraryStore.books.map((b) => b.id));
    for (const id of prevIds.current) {
      if (!currentIds.has(id)) {
        const url = coverMapRef.current[id];
        if (url) URL.revokeObjectURL(url);
        setCoverMap((prev) => { const n = { ...prev }; delete n[id]; return n; });
      }
    }
    prevIds.current = currentIds;
    for (const book of libraryStore.books) void loadCover(book);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [libraryStore.books]);

  useEffect(() => { libraryStore.ensureLoaded(); collectionsStore.ensureLoaded(); }, []);

  // When the active collection changes, re-filter the library and re-tally
  // tags. Skips the initial mount (ensureLoaded already covers it) — the Vue
  // watch had no `immediate`.
  const firstCollectionRun = useRef(true);
  const activeCollectionId = collectionsStore.activeCollectionId;
  useEffect(() => {
    if (firstCollectionRun.current) { firstCollectionRun.current = false; return; }
    useLibraryStore.setState({ collectionFilter: useCollectionsStore.getState().activeCollectionName });
    libraryStore.applySearch();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeCollectionId]);

  // Navigated here (e.g. from Tasks "view") with ?search=…: set the text box
  // and trigger a search. Runs on mount too (the Vue watch was `immediate`).
  const search = searchParams.get('search') ?? '';
  useEffect(() => {
    if (!search) return;
    // Always sync collectionFilter first so a prior setActiveCollection(null)
    // from another view takes effect.
    useLibraryStore.setState({ collectionFilter: useCollectionsStore.getState().activeCollectionName });
    if (search === useLibraryStore.getState().query) { libraryStore.applySearch(); return; }
    useLibraryStore.setState({ query: search });
    libraryStore.applySearch();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search]);

  // Revoke every cover URL on unmount (read through a ref — the cleanup
  // closure would otherwise capture the initial empty map).
  useEffect(() => () => {
    for (const url of Object.values(coverMapRef.current)) if (url) URL.revokeObjectURL(url);
  }, []);

  async function onImport() {
    const file = await api.openFile([{ name: t('lib.import.filterName'), extensions: ['cb7', 'cbz', 'cbr', 'epub', 'pdf'] }]);
    if (typeof file === 'string') {
      try { const book = await api.importBook(file); await libraryStore.refresh(); toast.addToast('success', t('lib.imported', { title: (book as any)?.title ?? '' })); }
      catch (e) { toast.addToast('error', t('lib.importFailed', { error: String(e) })); }
    }
  }

  async function deleteBookItem(book: Book) {
    try {
      await libraryStore.deleteBook(book.id);
      void deleteThumb(book.id);
      toast.addToast('success', t('lib.deleted', { title: book.title }));
    } catch (e) {
      toast.addToast('error', t('lib.deleteFailed', { error: String(e) }));
    }
  }

  return (
    <div className="pa-6">
      <div className="library-header d-flex align-center gap-4 mb-6" style={{ minHeight: 40 }}>
        <h2 className="text-h5" style={{ margin: 0, whiteSpace: 'nowrap' }}>{title}</h2>
        <span className="spacer" />
        <SearchBox value={libraryStore.query} placeholder={t('lib.search.placeholder')} clearLabel={t('common.clear')} onChange={(v) => useLibraryStore.setState({ query: v })} onCommit={() => libraryStore.applySearch()} />
        <button className="md3-btn md3-btn--filled" onClick={onImport}><MdiIcon path={mdiFolderOpen} size={20} /> {t('lib.import')}</button>
        {libraryStore.isLoading && <svg className="spinner" style={{ color: 'var(--md-sys-color-primary)', width: 24, height: 24 }} viewBox="0 0 50 50"><circle className="spinner-track" cx="25" cy="25" r="20" /><circle className="spinner-arc" cx="25" cy="25" r="20" /></svg>}
      </div>

      {libraryStore.allTags.length > 0 && (
        <div className="tag-chips mb-6">
          {libraryStore.allTags.map((tag) => (
            <button key={tag.name} className={`tag-chip${libraryStore.selectedTags.includes(tag.name) ? ' tag-chip--selected' : ''}`} aria-pressed={libraryStore.selectedTags.includes(tag.name)} onClick={() => libraryStore.toggleTag(tag.name)}>
              <span className="tag-chip__label">{tag.name}</span><span className="tag-chip__count">({tag.count})</span>
            </button>
          ))}
          {libraryStore.allTags.length >= TAG_DISPLAY_LIMIT && <span className="tag-chip tag-chip--ellipsis" aria-hidden="true">…</span>}
        </div>
      )}

      {libraryStore.books.length > 0 ? (
        <div className="md3-grid">
          {libraryStore.books.map((book) => (
            <div key={book.id}>
              <SourceCard id={`book-anchor-${book.id}`} title={book.title} pageCount={book.page_count} subtitle={book.author} cover={coverMap[book.id] ?? null}
                onClick={() => navigate(`/reader/${book.id}`)} onContextMenu={(e) => { e.preventDefault(); openMenu(book.id); }} />
              <BookMenu
                anchorId={`book-anchor-${book.id}`}
                open={openBookId === book.id}
                onClose={closeMenu}
                items={[
                  { icon: mdiPlaylistPlus, label: t('lib.collections.addTo'), action: () => openCollectionPicker(book.id) },
                  { icon: mdiInformationOutline, label: t('lib.viewMeta'), action: () => metaDialogRef.current?.open(book) },
                  { icon: mdiContentSave, label: t('lib.save'), action: () => exportDialogRef.current?.open(book) },
                  { icon: mdiDelete, label: t('lib.delete'), action: () => void deleteBookItem(book) },
                ]}
              />
            </div>
          ))}
        </div>
      ) : !libraryStore.isLoading ? <div className="text-center text-medium-emphasis mt-8">{t('lib.empty')}</div> : null}

      {libraryStore.books.length > 0 && (
        <div className="feed-sentinel-wrap">
          <div ref={sentinelRef} className="feed-sentinel" />
          {libraryStore.isLoadingMore && <div className="feed-loading"><svg className="spinner" style={{ color: 'var(--md-sys-color-primary)', width: 24, height: 24 }} viewBox="0 0 50 50"><circle className="spinner-track" cx="25" cy="25" r="20" /><circle className="spinner-arc" cx="25" cy="25" r="20" /></svg></div>}
        </div>
      )}

      <FabButton icon={mdiPlaylistPlay} ariaLabel={t('lib.collections.manage')} onClick={() => setShowCollectionDialog(true)} />
      {showCollectionDialog && <CollectionDialog onClose={() => setShowCollectionDialog(false)} />}
      {pickerBookId && <BookCollectionPicker bookId={pickerBookId} onClose={() => openCollectionPicker('')} />}
      <BookMetaDialog ref={metaDialogRef} />
      <BookExportDialog ref={exportDialogRef} />
    </div>
  );
}
