// src/views/Reader.vue
<template>
  <div
    class="reader fill-height"
    :class="{ 'reader--ui-hidden': uiHidden }"
    @mousemove="onMouseMove"
    @mouseleave="uiHidden = true"
  >
    <header class="reader-topbar">
      <button
        class="icon-btn"
        :title="t('reader.back')"
        :aria-label="t('reader.back')"
        @click="router.push('/library')"
      >
        <svg :width="22" :height="22" viewBox="0 0 24 24" fill="currentColor">
          <path :d="mdiArrowLeft" />
        </svg>
      </button>

      <div class="reader-topbar__title text-title-medium truncate">
        {{ title || t('reader.untitled') }}
      </div>

      <span class="spacer" />

      <div class="reader-actions">
        <button
          class="icon-btn"
          :title="zoomMode === 'fill' ? t('reader.fitScreen') : t('reader.fitContent')"
          :aria-label="zoomMode === 'fill' ? t('reader.fitScreen') : t('reader.fitContent')"
          @click="toggleZoom"
        >
          <svg :width="22" :height="22" viewBox="0 0 24 24" fill="currentColor">
            <path :d="zoomMode === 'fill' ? mdiImageSizeSelectActual : mdiImageSizeSelectLarge" />
          </svg>
        </button>
      </div>
    </header>

    <div
      class="reader-viewport"
      @click="onViewportClick"
    >
      <template v-if="src">
        <img
          :key="current"
          :src="src"
          :alt="t('reader.page', { page: current + 1 })"
          class="reader-image"
          :style="fitStyle"
          draggable="false"
        />
      </template>
      <template v-else>
        <div class="d-flex flex-column align-center justify-center ga-3">
          <md-circular-progress indeterminate />
          <span class="text-body-2">
            {{ t('reader.loadingPage', { page: current + 1, total: pageCount ?? '?' }) }}
          </span>
        </div>
      </template>
    </div>

    <div class="reader-footer d-flex align-center ga-3 px-4 py-2">
      <span class="reader-page-label text-body-2">{{ current + 1 }}</span>

      <md-slider
        v-if="pageCount != null"
        ref="sliderRef"
        class="flex-grow-1"
        :min="0"
        :max="Math.max(0, pageCount - 1)"
        :step="1"
        ticks
      />

      <span class="reader-page-label text-body-2">{{ pageCount ?? '?' }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  mdiArrowLeft,
  mdiImageSizeSelectLarge,
  mdiImageSizeSelectActual,
} from '@mdi/js';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { api } from '@/services/api';
import { useI18n } from '@/i18n';
import { applyMd3Theme } from '@/services/md3-theme';
import { useThemeStore } from '@/stores/theme';
import type { Seed } from '@/services/md3-theme';

type ZoomMode = 'fill' | 'contain';

const props = defineProps<{
  id: string;
}>();

const { t } = useI18n();
const router = useRouter();

const pageCount = ref<number | null>(null);
const title = ref('');
const blobs = ref<Record<number, string>>({});
const current = ref(0);
const zoomMode = ref<ZoomMode>(readZoomMode());
const uiHidden = ref(false);
let uiHideTimer: ReturnType<typeof setTimeout> | null = null;

watch(zoomMode, (v) => saveZoomMode(v));
watch(current, (v) => saveBookProgress(props.id, v));

const src = computed(() => blobs.value[current.value]);

const fitStyle = computed(() => {
  if (zoomMode.value === 'fill') {
    return { width: '100%', height: '100%', objectFit: 'cover' as const };
  }
  return {
    width: 'auto',
    height: 'auto',
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain' as const,
  };
});

function readZoomMode(): ZoomMode {
  try {
    const saved = window.localStorage.getItem('erolib.reader.zoomMode');
    if (saved === 'fill' || saved === 'contain') return saved;
  } catch {
    // ignore
  }
  return 'contain';
}

function saveZoomMode(mode: ZoomMode) {
  try {
    window.localStorage.setItem('erolib.reader.zoomMode', mode);
  } catch {
    // ignore
  }
}

function readBookProgress(bookId: string): number {
  try {
    const raw = window.localStorage.getItem(`erolib.reader.progress.${bookId}`);
    const parsed = raw ? Number(raw) : 0;
    return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0;
  } catch {
    return 0;
  }
}

function saveBookProgress(bookId: string, page: number) {
  try {
    window.localStorage.setItem(`erolib.reader.progress.${bookId}`, String(page));
  } catch {
    // ignore
  }
}

/** Guess a mime type from magic bytes so blob URLs render all stored formats. */
function mimeFromBytes(bytes: number[]): string {
  const b = bytes.slice(0, 12);
  if (b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return 'image/jpeg';
  if (b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47) return 'image/png';
  if (
    b[0] === 0x52 &&
    b[1] === 0x49 &&
    b[2] === 0x46 &&
    b[3] === 0x46 &&
    b[8] === 0x57 &&
    b[9] === 0x45 &&
    b[10] === 0x42 &&
    b[11] === 0x50
  )
    return 'image/webp';
  return 'image/jpeg';
}

function setCurrent(value: number) {
  if (pageCount.value == null) return;
  current.value = Math.max(0, Math.min(pageCount.value - 1, value));
}

function go(delta: number) {
  setCurrent(current.value + delta);
}

function onViewportClick(e: MouseEvent) {
  const target = e.currentTarget as HTMLElement;
  const rect = target.getBoundingClientRect();
  const x = e.clientX - rect.left;
  if (x > rect.width / 2) go(1);
  else go(-1);
}

function onKeyDown(e: KeyboardEvent) {
  if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
  if (e.key === 'ArrowRight' || e.key === 'PageDown' || e.key === ' ') {
    e.preventDefault();
    go(1);
  } else if (e.key === 'ArrowLeft' || e.key === 'PageUp') {
    e.preventDefault();
    go(-1);
  }
}

function clearBlobs() {
  Object.values(blobs.value).forEach(URL.revokeObjectURL);
  blobs.value = {};
}

async function loadMetadata() {
  if (!props.id) return;
  try {
    const [book, count] = await Promise.all([
      api.getBook(props.id),
      api.getBookPageCount(props.id),
    ]);
    title.value = book.title;
    pageCount.value = count;
    const saved = readBookProgress(props.id);
    current.value = Math.min(saved, Math.max(0, count - 1));
  } catch (e) {
    console.error('Failed to load book:', e);
  }
}

async function prefetchPages() {
  if (!props.id || pageCount.value == null) return;
  const span = 2;
  const pages: number[] = [];
  for (let p = current.value; p <= Math.min(pageCount.value - 1, current.value + span); p++) {
    if (!blobs.value[p]) pages.push(p);
  }

  for (const p of pages) {
    try {
      const bytes = await api.getBookPage(props.id, p);
      const blob = new Blob([new Uint8Array(bytes)], { type: mimeFromBytes(bytes) });
      const url = URL.createObjectURL(blob);
      blobs.value[p] = url;
    } catch (e) {
      console.warn(`Failed to load page ${p}:`, e);
    }
  }
}

function toggleZoom() {
  zoomMode.value = zoomMode.value === 'fill' ? 'contain' : 'fill';
}

function onMouseMove() {
  uiHidden.value = false;
  if (uiHideTimer) clearTimeout(uiHideTimer);
  uiHideTimer = setTimeout(() => {
    uiHidden.value = true;
  }, 2000);
}

/** Force dark theme while Reader is mounted, restore on leave. */
const previousMode = ref<'light' | 'dark' | null>(null);
const previousSeed = ref<Seed | null>(null);
const themeStore = useThemeStore();

onMounted(() => {
  loadMetadata();
  window.addEventListener('keydown', onKeyDown);
  previousMode.value = themeStore.mode;
  previousSeed.value = themeStore.seed;
  applyMd3Theme(themeStore.seed, 'dark');
});

onBeforeUnmount(() => {
  window.removeEventListener('keydown', onKeyDown);
  clearBlobs();
  if (uiHideTimer) clearTimeout(uiHideTimer);
  if (previousMode.value && previousSeed.value) {
    applyMd3Theme(previousSeed.value, previousMode.value);
  }
});

watch(() => props.id, () => {
  current.value = 0;
  clearBlobs();
  loadMetadata();
});

watch([current, pageCount], () => {
  prefetchPages();
});

// Sync MWC slider with current page.
type MdSlider = HTMLElement & { value: number };
const sliderRef = ref<MdSlider | null>(null);
function syncSliderValue() {
  if (sliderRef.value) {
    sliderRef.value.value = current.value;
  }
}

function onSliderInput() {
  if (sliderRef.value) {
    const next = Number(sliderRef.value.value);
    if (!Number.isNaN(next)) {
      setCurrent(next);
    }
  }
}

function bindSlider() {
  if (!sliderRef.value) return;
  syncSliderValue();
  sliderRef.value.addEventListener('input', onSliderInput);
  sliderRef.value.addEventListener('change', onSliderInput);
}

function unbindSlider() {
  sliderRef.value?.removeEventListener('input', onSliderInput);
  sliderRef.value?.removeEventListener('change', onSliderInput);
}

watch(current, syncSliderValue);
watch(sliderRef, (el, prev) => {
  if (prev) unbindSlider();
  if (el) bindSlider();
});
onMounted(() => {
  bindSlider();
});
onBeforeUnmount(() => {
  unbindSlider();
});
</script>

<style scoped>
.reader {
  position: relative;
  overflow: hidden;
  background: var(--md-sys-color-surface);
}

.reader-topbar,
.reader-footer {
  position: absolute;
  left: 0;
  right: 0;
  z-index: 10;
  transition:
    opacity 0.25s ease,
    transform 0.25s ease;
}

.reader-topbar {
  top: 0;
  display: flex;
  align-items: center;
  gap: 12px;
  min-height: 64px;
  padding: 8px 16px;
  border-bottom: 1px solid var(--md-sys-color-outline-variant);
  background: color-mix(in srgb, var(--md-sys-color-surface) 85%, transparent);
  backdrop-filter: blur(8px);
}

.reader-footer {
  bottom: 0;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 16px;
  border-top: 1px solid var(--md-sys-color-outline-variant);
  background: color-mix(in srgb, var(--md-sys-color-surface) 85%, transparent);
  backdrop-filter: blur(8px);
}

.reader--ui-hidden .reader-topbar,
.reader--ui-hidden .reader-footer {
  opacity: 0;
  pointer-events: none;
}

.reader--ui-hidden .reader-topbar {
  transform: translateY(-100%);
}

.reader--ui-hidden .reader-footer {
  transform: translateY(100%);
}

.reader-topbar__title {
  flex: 0 1 auto;
  min-width: 0;
  color: var(--md-sys-color-on-surface);
  font: var(--md-sys-typescale-title-medium-weight)
    var(--md-sys-typescale-title-medium-size) /
    var(--md-sys-typescale-title-medium-line-height)
    var(--md-sys-typescale-font);
}

.reader-actions {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  gap: 4px;
}

.icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  padding: 0;
  border: none;
  border-radius: var(--md-sys-shape-corner-full);
  background: transparent;
  color: var(--md-sys-color-on-surface-variant);
  cursor: pointer;
  transition: background-color 0.15s ease;
}

.icon-btn:hover {
  background: color-mix(in srgb, var(--md-sys-color-on-surface) 8%, transparent);
}

.spacer {
  flex: 1 1 auto;
}

.reader-page-label {
  min-width: 28px;
  text-align: center;
  font-variant-numeric: tabular-nums;
  color: var(--md-sys-color-on-surface);
}

.reader-viewport {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: auto;
  background: var(--md-sys-color-surface);
  cursor: pointer;
}

.reader-image {
  display: block;
  max-width: none;
  max-height: none;
  user-select: none;
}

.truncate {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
</style>

// src/views/Reader.tsx
import { useParams, useNavigate } from 'react-router-dom';
import { useState, useEffect, useRef } from 'react';
import { useI18n } from '@/hooks/useI18n';
import { useThemeStore } from '@/stores/theme';
import { api } from '@/services/api';
import { mdiArrowLeft, mdiImageSizeSelectActual, mdiImageSizeSelectLarge } from '@mdi/js';

export default function Reader() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { t } = useI18n();

  const [title, setTitle] = useState('');
  const [pageCount, setPageCount] = useState(0);
  const [current, setCurrent] = useState(0);
  const [src, setSrc] = useState<string | null>(null);
  const [zoomMode, setZoomMode] = useState<'fill' | 'contain'>('contain');
  const [loading, setLoading] = useState(true);
  const blobs = useRef<Record<number, string>>({});
  const viewportRef = useRef<HTMLDivElement>(null);

  // Force dark mode
  const prevSeed = useRef(useThemeStore.getState().seed);
  const prevMode = useRef(useThemeStore.getState().mode);
  useEffect(() => {
    useThemeStore.getState().setMode('dark');
    return () => { useThemeStore.getState().setSeed(prevSeed.current); useThemeStore.getState().setMode(prevMode.current); };
  }, []);

  // Load book
  useEffect(() => {
    if (!id) return;
    void (async () => {
      try {
        const book = await api.getBook(id);
        setTitle(book.title);
        const count = await api.getBookPageCount(id);
        setPageCount(count);
        await loadPage(0);
        setLoading(false);
      } catch { setLoading(false); }
    })();
    return () => { for (const url of Object.values(blobs.current)) URL.revokeObjectURL(url); };
  }, [id]);

  async function loadPage(idx: number) {
    if (blobs.current[idx]) { setSrc(blobs.current[idx]); return; }
    try {
      const bytes = await api.getBookPage(id!, idx);
      const blob = new Blob([new Uint8Array(bytes)]);
      const url = URL.createObjectURL(blob);
      blobs.current[idx] = url;
      setSrc(url);
    } catch { /* ignore */ }
  }

  function goTo(idx: number) {
    const clamped = Math.max(0, Math.min(idx, pageCount - 1));
    setCurrent(clamped);
    void loadPage(clamped);
  }

  function onViewportClick(e: React.MouseEvent) {
    const rect = viewportRef.current?.getBoundingClientRect();
    if (!rect) return;
    const x = e.clientX - rect.left;
    if (x < rect.width / 3) goTo(current - 1);
    else if (x > rect.width * 2 / 3) goTo(current + 1);
  }

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      if (e.key === 'ArrowRight' || e.key === 'PageDown') { goTo(current + 1); e.preventDefault(); }
      else if (e.key === 'ArrowLeft' || e.key === 'PageUp') { goTo(current - 1); e.preventDefault(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [current, pageCount]);

  return (
    <div className="reader fill-height" style={{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#000', color: '#fff' }}>
      <header style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 16px', background: 'rgba(0,0,0,0.8)', zIndex: 10 }}>
        <button onClick={() => navigate(-1)} style={{ background: 'none', border: 'none', color: '#fff', cursor: 'pointer', padding: 8, borderRadius: '50%' }} title={t('reader.back')}>
          <svg width={22} height={22} viewBox="0 0 24 24" fill="currentColor"><path d={mdiArrowLeft} /></svg>
        </button>
        <div style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontSize: 16 }}>{title || t('reader.untitled')}</div>
        <button onClick={() => setZoomMode(zoomMode === 'fill' ? 'contain' : 'fill')} style={{ background: 'none', border: 'none', color: '#fff', cursor: 'pointer', padding: 8, borderRadius: '50%' }}>
          <svg width={22} height={22} viewBox="0 0 24 24" fill="currentColor"><path d={zoomMode === 'fill' ? mdiImageSizeSelectActual : mdiImageSizeSelectLarge} /></svg>
        </button>
      </header>
      <div ref={viewportRef} onClick={onViewportClick} style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', minHeight: 0 }}>
        {src ? (
          <img src={src} alt={`Page ${current + 1}`} style={zoomMode === 'fill' ? { width: '100%', height: '100%', objectFit: 'cover' } : { maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} draggable={false} />
        ) : loading ? (
          <div style={{ textAlign: 'center' }}><svg className="spinner" style={{ color: 'var(--md-sys-color-primary)' }} viewBox="0 0 50 50"><circle className="spinner-track" cx="25" cy="25" r="20" /><circle className="spinner-arc" cx="25" cy="25" r="20" /></svg></div>
        ) : null}
      </div>
      <footer style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 16px', background: 'rgba(0,0,0,0.8)' }}>
        <span style={{ fontSize: 14 }}>{current + 1}</span>
        <input type="range" min={0} max={Math.max(0, pageCount - 1)} value={current} onChange={(e) => goTo(Number(e.target.value))} style={{ flex: 1 }} />
        <span style={{ fontSize: 14 }}>{pageCount || '?'}</span>
      </footer>
    </div>
  );
}
