// src/views/Tasks.vue
<template>
  <div class="tasks-view pa-6">
    <div class="tasks-header d-flex align-center gap-4 mb-6">
      <h2 class="text-h5 tasks-header__title">{{ t('tasks.title') }}</h2>
    </div>

    <div v-if="taskStore.loading" class="empty-state">
      <FeedLoading />
    </div>

    <div v-else-if="taskStore.tasks.length === 0" class="empty-state">
      <p class="text-body-1 text-medium-emphasis">{{ t('tasks.empty') }}</p>
    </div>

    <div v-else class="task-list">
      <div
        v-for="item in taskStore.tasks"
        :key="item.id"
        class="md3-card md3-card--outlined task-card"
        :class="{ 'task-card--selected': taskStore.selectedTaskId === item.id }"
        @click="selectTask(item.id)"
      >
        <div class="task-header">
          <span class="task-title">{{ item.title }}</span>
          <span class="task-status" :class="'status--' + item.status">
            {{ t('tasks.status.' + item.status) }}
          </span>
        </div>

        <div class="task-progress">
          <div class="progress-bar-bg">
            <div
              class="progress-bar-fill"
              :style="{ width: progressPercent(item) + '%' }"
            />
          </div>
          <span class="progress-text text-body-3">
            {{ progressPercent(item) }}%
          </span>
        </div>

        <!-- Inline logs: <details> handles expand/collapse natively.
             The `open` attr is driven by selectedTaskId so clicking a different
             card collapses the old one and expands the new one. -->
        <details
          class="task-logs-wrap"
          :open="taskStore.selectedTaskId === item.id"
          @toggle.prevent
          @contextmenu.prevent="copyLogs(item)"
        >
          <summary class="task-logs-summary" />
          <div class="task-logs-inner">
            <div v-if="item.logs.length" class="logs-list">
              <div
                v-for="(line, i) in item.logs"
                :key="i"
                class="log-line text-body-2"
              >
                {{ line }}
              </div>
            </div>
            <p v-else class="text-body-2 text-medium-emphasis logs-empty">
              {{ t('tasks.detail.noLogs') }}
            </p>
          </div>
        </details>

        <div class="task-footer">
          <div class="task-actions">
            <!-- Completed tasks: show "View" button that navigates to Library
                 and searches the book by title. -->
            <md-filled-button
              v-if="item.status === 'completed' && item.book_id"
              @click.stop="viewInLibrary(item.title)"
            >
              <MdiIcon slot="icon" :path="mdiMagnify" :size="18" />
              {{ t('tasks.actions.view') }}
            </md-filled-button>

            <md-filled-tonal-button
              v-if="item.status === 'running'"
              @click.stop="taskStore.pauseTask(item.id)"
            >
              <MdiIcon slot="icon" :path="mdiPause" :size="18" />
              {{ t('tasks.actions.pause') }}
            </md-filled-tonal-button>

            <md-filled-tonal-button
              v-if="item.status === 'paused'"
              @click.stop="taskStore.resumeTask(item.id)"
            >
              <MdiIcon slot="icon" :path="mdiPlay" :size="18" />
              {{ t('tasks.actions.resume') }}
            </md-filled-tonal-button>

            <md-filled-tonal-button
              v-if="item.status === 'running' || item.status === 'paused'"
              @click.stop="taskStore.cancelTask(item.id)"
            >
              <MdiIcon slot="icon" :path="mdiClose" :size="18" />
              {{ t('tasks.actions.cancel') }}
            </md-filled-tonal-button>

            <md-filled-tonal-button
              v-if="item.status === 'failed'"
              @click.stop="taskStore.retryTask(item.id)"
            >
              <MdiIcon slot="icon" :path="mdiRefresh" :size="18" />
              {{ t('tasks.actions.retry') }}
            </md-filled-tonal-button>

            <md-outlined-button
              v-if="item.status === 'completed'"
              :disabled="redownloadingId === item.id"
              @click.stop="onRedownload(item)"
            >
              <MdiIcon slot="icon" :path="mdiDownload" :size="18" />
              {{ t('tasks.actions.redownload') }}
            </md-outlined-button>

            <md-outlined-button
              v-if="item.status === 'completed' || item.status === 'failed' || item.status === 'cancelled'"
              @click.stop="taskStore.deleteTask(item.id)"
            >
              <MdiIcon slot="icon" :path="mdiDelete" :size="18" />
              {{ t('tasks.actions.remove') }}
            </md-outlined-button>
          </div>

          <span v-if="item.status === 'running'" class="task-speed">
            {{ formatSpeed(item.speed, t) }}
          </span>
          <span v-else-if="item.status === 'completed'" class="task-speed">
            {{ t('tasks.summary', { size: formatBytes(item.total_bytes, t), time: formatDuration(item.elapsed_ms, t) }) }}
          </span>
        </div>
      </div>
    </div>

    <FabButton
      v-if="hasRetryable"
      :icon="mdiRestart"
      :aria-label="t('tasks.actions.retryAll')"
      :disabled="retrying"
      style="bottom: 96px"
      @click="onRetryAll"
    />
    <FabButton
      v-if="hasCompleted"
      :icon="mdiBroom"
      :aria-label="t('tasks.actions.clearCompleted')"
      :disabled="clearing"
      @click="onClearCompleted"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import '@material/web/button/outlined-button.js';
import '@material/web/button/filled-tonal-button.js';
import {
  mdiPause,
  mdiPlay,
  mdiClose,
  mdiDelete,
  mdiRefresh,
  mdiMagnify,
  mdiBroom,
  mdiRestart,
  mdiDownload,
} from '@mdi/js';
import { useI18n } from '@/i18n';
import { useTaskStore } from '@/stores/tasks';
import { useToastStore } from '@/stores/toast';
import { useCollectionsStore } from '@/stores/collections';
import MdiIcon from '@/components/MdiIcon.vue';
import FabButton from '@/components/FabButton.vue';
import FeedLoading from '@/components/FeedLoading.vue';
import { formatBytes, formatSpeed, formatDuration } from '@/utils/format';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';

const { t } = useI18n();
const router = useRouter();
const toastStore = useToastStore();
const taskStore = useTaskStore();
const collectionsStore = useCollectionsStore();

const clearing = ref(false);
const retrying = ref(false);

const hasCompleted = computed(() => taskStore.tasks.some((tk) => tk.status === 'completed'));
const hasRetryable = computed(() => taskStore.tasks.some((tk) => tk.status === 'failed' || tk.status === 'paused'));

function progressPercent(item: { progress_current: number; progress_total: number }): number {
  if (item.progress_total <= 0) return 100;
  return Math.min(100, Math.round((item.progress_current / item.progress_total) * 100));
}

function selectTask(id: string) {
  // Clicking the already-open card is a no-op; clicking a different card
  // collapses the previous one and expands the new one.
  if (taskStore.selectedTaskId === id) return;
  taskStore.selectTask(id);
}

/**
 * Task titles are formatted as "{Source}: {actual book title}" (e.g.
 * "ASMHentai: ある作品"). Strip the source prefix so the search matches
 * the bare book title registered in the library.
 */
function extractBookTitle(taskTitle: string): string {
  // Known prefixes: "Pixiv: ", "EHentai: ", "EXHentai: ", "ASMHentai: ",
  // "NiceCat: ".  Strip the first "Prefix: " segment if present.
  return taskTitle.replace(/^[A-Za-z]+:\s*/, '');
}

function viewInLibrary(taskTitle: string) {
  // Switch back to "All" so the user can see all books, then search by title.
  collectionsStore.setActiveCollection(null);
  const title = extractBookTitle(taskTitle);
  router.push({ path: '/library', query: { search: title } });
}

async function onClearCompleted() {
  clearing.value = true;
  try {
    const before = taskStore.tasks.filter((tk) => tk.status === 'completed').length;
    await taskStore.clearCompleted();
    toastStore.addToast('info', t('tasks.toast.cleared', { count: before }));
  } catch (e) {
    toastStore.addToast('error', t('common.error', { message: String(e) }));
  } finally {
    clearing.value = false;
  }
}

async function onRetryAll() {
  retrying.value = true;
  try {
    await taskStore.retryAll();
    toastStore.addToast('info', t('tasks.toast.retried'));
  } catch (e) {
    toastStore.addToast('error', t('common.error', { message: String(e) }));
  } finally {
    retrying.value = false;
  }
}

const redownloadingId = ref<string | null>(null);
async function onRedownload(item: import('@/services/api').TaskItem) {
  // Global debounce: only one re-download at a time (the backend has its own
  // guards, but this also keeps the UX from firing twice on a double-click).
  if (redownloadingId.value) return;
  redownloadingId.value = item.id;
  try {
    const action = await taskStore.redownloadTask(item.id);
    const title = extractBookTitle(item.title);
    if (action === 'already_complete') {
      toastStore.addToast('info', t('tasks.toast.alreadyComplete', { title }));
    } else {
      toastStore.addToast('success', t('tasks.toast.redownloadStarted', { title }));
    }
  } catch (e) {
    toastStore.addToast('error', t('tasks.toast.redownloadFailed', { message: String(e) }));
  } finally {
    redownloadingId.value = null;
  }
}

async function copyLogs(item: import('@/services/api').TaskItem) {
  if (!item.logs.length) return;
  const text = item.logs.join('\n');
  try {
    await writeText(text);
    toastStore.addToast('success', t('tasks.logs.copied'));
  } catch (e) {
    console.error('[Tasks] copyLogs failed:', e);
    toastStore.addToast('error', t('tasks.logs.copyFailed'));
  }
}

onMounted(async () => {
  await taskStore.init();
});
</script>

<style scoped>
/* Title aligns with the other views — clear the h2 default margin-block that
   was making this header row taller than Library/Pixiv/EHentai. */
.tasks-header__title {
  margin: 0;
}

.task-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.task-card {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  border-radius: var(--md-sys-shape-corner-medium);
  background: var(--md-sys-color-surface);
  border: 1px solid var(--md-sys-color-outline-variant);
  cursor: pointer;
  transition:
    background-color 0.15s ease,
    border-color 0.15s ease;
}

.task-card:hover {
  background: var(--md-sys-color-surface-container);
}

.task-card--selected {
  border-color: var(--md-sys-color-primary);
}

.task-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.task-title {
  font: 500 var(--md-sys-typescale-title-medium-size) / var(--md-sys-typescale-title-medium-line-height) var(--md-sys-typescale-font);
  color: var(--md-sys-color-on-surface);
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.task-status {
  font: 500 var(--md-sys-typescale-label-medium-size) / var(--md-sys-typescale-label-medium-line-height) var(--md-sys-typescale-font);
  padding: 2px 10px;
  border-radius: var(--md-sys-shape-corner-small);
  flex-shrink: 0;
}

.status--running {
  background: var(--md-sys-color-tertiary-container);
  color: var(--md-sys-color-on-tertiary-container);
}

.status--pending {
  background: var(--md-sys-color-secondary-container);
  color: var(--md-sys-color-on-secondary-container);
}

.status--paused {
  background: var(--md-sys-color-surface-variant);
  color: var(--md-sys-color-on-surface-variant);
}

.status--completed {
  background: var(--md-sys-color-primary-container);
  color: var(--md-sys-color-on-primary-container);
}

.status--failed {
  background: #fce4ec;
  color: #c62828;
}

.status--cancelled {
  background: var(--md-sys-color-surface-variant);
  color: var(--md-sys-color-on-surface-variant);
}

.task-detail-line {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.task-progress {
  display: flex;
  align-items: center;
  gap: 12px;
}

.progress-bar-bg {
  flex: 1;
  height: 6px;
  background: var(--md-sys-color-surface-variant);
  border-radius: 3px;
  overflow: hidden;
}

.progress-bar-fill {
  height: 100%;
  background: var(--md-sys-color-primary);
  border-radius: 3px;
  transition: width 0.3s ease;
}

.progress-text {
  flex-shrink: 0;
  color: var(--md-sys-color-on-surface-variant);
}

/* Inline logs: smoothly expand when the card is selected. <details> provides
   the expand/collapse mechanics; the summary decoy hides the native arrow. */
.task-logs-wrap {
  overflow: hidden;
  opacity: 0;
  transition:
    opacity 0.2s ease,
    margin 0.2s ease;
}
.task-logs-wrap[open] {
  opacity: 1;
}

/* Hide the native <summary> arrow — the open/close state is driven by
   card selection, not by clicking the summary itself. */
.task-logs-summary {
  display: none;
}

.task-logs-inner {
  display: flex;
  flex-direction: column;
}

.logs-list {
  max-height: 220px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 8px 10px;
  border-radius: var(--md-sys-shape-corner-small);
  background: var(--md-sys-color-surface-variant);
}

.logs-empty {
  padding: 8px 10px;
}

.log-line {
  color: var(--md-sys-color-on-surface-variant);
  font-family: var(--md-sys-typescale-font);
  font-variant-numeric: tabular-nums;
  word-break: break-word;
  white-space: pre-wrap;
}

.task-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.task-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.task-speed {
  font: 500 var(--md-sys-typescale-label-medium-size) / var(--md-sys-typescale-label-medium-line-height) var(--md-sys-typescale-font);
  font-variant-numeric: tabular-nums;
  color: var(--md-sys-color-on-surface-variant);
  flex-shrink: 0;
  min-width: 78px;
  text-align: right;
}

.empty-state {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 200px;
}

.tasks-header {
  flex-wrap: wrap;
  /* Match the row height the other views get from their header button (40px is
     the MD3 button container height), so this title aligns vertically with
     Library/Pixiv/EHentai even though it has no action button. */
  min-height: 40px;
}

.spacer {
  flex: 1 1 auto;
}
</style>

// src/views/Tasks.tsx
import { useEffect, useState, useRef } from 'react';
import { useI18n } from '@/hooks/useI18n';
import { useTaskStore } from '@/stores/tasks';
import { useToastStore } from '@/stores/toast';
import { useCollectionsStore } from '@/stores/collections';
import { useNavigate } from 'react-router-dom';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';
import { MdiIcon } from '@/components/MdiIcon';
import { FabButton } from '@/components/FabButton';
import { FeedLoading } from '@/components/FeedLoading';
import { formatBytes, formatSpeed, formatDuration } from '@/utils/format';
import {
  mdiPause, mdiPlay, mdiClose, mdiDelete, mdiRefresh, mdiMagnify, mdiBroom, mdiRestart, mdiDownload,
} from '@mdi/js';
import { M3eButton } from '@m3e/react/button';
import type { TaskItem } from '@/services/api';

export default function Tasks() {
  const { t } = useI18n();
  const navigate = useNavigate();
  const taskStore = useTaskStore();
  const toast = useToastStore();
  const collectionsStore = useCollectionsStore();
  const [redownloadingId, setRedownloadingId] = useState<string | null>(null);
  const [clearing, setClearing] = useState(false);
  const [retrying, setRetrying] = useState(false);
  const hasCompleted = taskStore.tasks.some((t) => t.status === 'completed');
  const hasRetryable = taskStore.tasks.some((t) => t.status === 'failed' || t.status === 'paused');

  useEffect(() => { void taskStore.init(); }, []);

  function progressPercent(item: TaskItem): number {
    // Unknown total counts as complete; never exceed 100%.
    if (item.progress_total <= 0) return 100;
    return Math.min(100, Math.round((item.progress_current / item.progress_total) * 100));
  }

  /**
   * Task titles are formatted as "{Source}: {actual book title}" (e.g.
   * "ASMHentai: ある作品"). Strip the first "Prefix: " segment so the search
   * matches the bare book title registered in the library.
   */
  function extractBookTitle(taskTitle: string): string {
    return taskTitle.replace(/^[A-Za-z]+:\s*/, '');
  }

  async function viewInLibrary(taskTitle: string) {
    collectionsStore.setActiveCollection(null);
    const title = extractBookTitle(taskTitle);
    navigate(`/library?search=${encodeURIComponent(title)}`);
  }

  async function onClearCompleted() {
    setClearing(true);
    try {
      const before = taskStore.tasks.filter((tk) => tk.status === 'completed').length;
      await taskStore.clearCompleted();
      toast.addToast('info', t('tasks.toast.cleared', { count: before }));
    } catch (e) {
      toast.addToast('error', t('common.error', { message: String(e) }));
    } finally {
      setClearing(false);
    }
  }

  async function onRetryAll() {
    setRetrying(true);
    try {
      await taskStore.retryAll();
      toast.addToast('info', t('tasks.toast.retried'));
    } catch (e) {
      toast.addToast('error', t('common.error', { message: String(e) }));
    } finally {
      setRetrying(false);
    }
  }

  async function onRedownload(item: TaskItem) {
    // Global debounce: only one re-download at a time.
    if (redownloadingId) return;
    setRedownloadingId(item.id);
    try {
      const action = await taskStore.redownloadTask(item.id);
      const title = extractBookTitle(item.title);
      if (action === 'already_complete') toast.addToast('info', t('tasks.toast.alreadyComplete', { title }));
      else toast.addToast('success', t('tasks.toast.redownloadStarted', { title }));
    } catch (e) { toast.addToast('error', t('tasks.toast.redownloadFailed', { message: String(e) })); }
    finally { setRedownloadingId(null); }
  }

  async function copyLogs(item: TaskItem) {
    if (!item.logs.length) return;
    try {
      await writeText(item.logs.join('\n'));
      toast.addToast('success', t('tasks.logs.copied'));
    } catch (e) {
      console.error('[Tasks] copyLogs failed:', e);
      toast.addToast('error', t('tasks.logs.copyFailed'));
    }
  }

  const statusColor: Record<string, string> = {
    running: 'var(--md-sys-color-tertiary-container)', pending: 'var(--md-sys-color-secondary-container)',
    paused: 'var(--md-sys-color-surface-variant)', completed: 'var(--md-sys-color-primary-container)',
    failed: 'var(--md-sys-color-error-container)', cancelled: 'var(--md-sys-color-surface-variant)',
  };

  return (
    <div className="pa-6">
      {/* tasks-header 语义对齐：Vue 中标题在 v-if 链之外，loading/空态也常驻 */}
      <div className="d-flex align-center gap-4 mb-6" style={{ flexWrap: 'wrap', minHeight: 40 }}>
        <h2 className="text-h5" style={{ margin: 0 }}>{t('tasks.title')}</h2>
      </div>
      {taskStore.loading ? (
        <div className="empty-state"><FeedLoading /></div>
      ) : taskStore.tasks.length === 0 ? (
        // empty-state 语义对齐：200px 垂直居中
        <div className="empty-state"><p className="text-body-1 text-medium-emphasis">{t('tasks.empty')}</p></div>
      ) : (
      <div className="task-list">
        {taskStore.tasks.map((item) => (
          <div
            key={item.id}
            className={`md3-card md3-card--outlined task-card${taskStore.selectedTaskId === item.id ? ' task-card--selected' : ''}`}
            onClick={() => taskStore.selectTask(item.id)}
          >
            <div className="d-flex align-center" style={{ gap: 12 }}>
              <span className="text-truncate" style={{ flex: 1, fontWeight: 500, minWidth: 0 }}>{item.title}</span>
              <span style={{ padding: '2px 10px', borderRadius: 'var(--md-sys-shape-corner-small)', fontSize: 12, background: statusColor[item.status] || 'var(--md-sys-color-surface-container)', whiteSpace: 'nowrap' }}>
                {t('tasks.status.' + item.status)}
              </span>
            </div>
            <div className="d-flex align-center" style={{ gap: 12 }}>
              <div style={{ flex: 1, height: 6, borderRadius: 3, background: 'var(--md-sys-color-surface-variant)', overflow: 'hidden' }}>
                <div style={{ width: progressPercent(item) + '%', height: '100%', borderRadius: 3, background: 'var(--md-sys-color-primary)', transition: 'width 0.3s ease' }} />
              </div>
              <span style={{ minWidth: 36, textAlign: 'right', color: 'var(--md-sys-color-on-surface-variant)' }}>{progressPercent(item)}%</span>
            </div>
            {/* task-logs-wrap 语义对齐：选中展开时 0.2s 淡入 */}
            {taskStore.selectedTaskId === item.id && (
              <div className="task-logs-body" onContextMenu={(e) => { e.preventDefault(); copyLogs(item); }} style={{ maxHeight: 220, overflowY: 'auto', fontSize: 12, padding: '8px 10px', borderRadius: 'var(--md-sys-shape-corner-small)', background: 'var(--md-sys-color-surface-variant)', color: 'var(--md-sys-color-on-surface-variant)', fontFamily: 'var(--md-sys-typescale-font)', fontVariantNumeric: 'tabular-nums', wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>
                {item.logs.length > 0 ? item.logs.map((line, i) => <div key={i} style={{ marginBottom: 2 }}>{line}</div>) : <div>{t('tasks.detail.noLogs')}</div>}
              </div>
            )}
            {/* task-footer 语义对齐：按钮行 + 右侧速度/摘要同行（space-between） */}
            <div className="task-footer">
              <div className="task-actions">
                {item.status === 'completed' && item.book_id && (
                  <M3eButton variant="filled" onClick={(e) => { e.stopPropagation(); viewInLibrary(item.title); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiMagnify} size={18} /> {t('tasks.actions.view')}
                  </M3eButton>
                )}
                {item.status === 'running' && (
                  <M3eButton variant="tonal" onClick={(e) => { e.stopPropagation(); void taskStore.pauseTask(item.id); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiPause} size={18} /> {t('tasks.actions.pause')}
                  </M3eButton>
                )}
                {item.status === 'paused' && (
                  <M3eButton variant="tonal" onClick={(e) => { e.stopPropagation(); void taskStore.resumeTask(item.id); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiPlay} size={18} /> {t('tasks.actions.resume')}
                  </M3eButton>
                )}
                {(item.status === 'running' || item.status === 'paused') && (
                  <M3eButton variant="tonal" onClick={(e) => { e.stopPropagation(); void taskStore.cancelTask(item.id); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiClose} size={18} /> {t('tasks.actions.cancel')}
                  </M3eButton>
                )}
                {item.status === 'failed' && (
                  <M3eButton variant="tonal" onClick={(e) => { e.stopPropagation(); void taskStore.retryTask(item.id); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiRefresh} size={18} /> {t('tasks.actions.retry')}
                  </M3eButton>
                )}
                {item.status === 'completed' && (
                  <M3eButton variant="outlined" disabled={redownloadingId === item.id} onClick={(e) => { e.stopPropagation(); void onRedownload(item); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiDownload} size={18} /> {t('tasks.actions.redownload')}
                  </M3eButton>
                )}
                {(item.status === 'completed' || item.status === 'failed' || item.status === 'cancelled') && (
                  <M3eButton variant="outlined" onClick={(e) => { e.stopPropagation(); void taskStore.deleteTask(item.id); }} style={{ fontSize: 13 }}>
                    <MdiIcon path={mdiDelete} size={18} /> {t('tasks.actions.remove')}
                  </M3eButton>
                )}
              </div>
              {item.status === 'running' && (
                <span className="task-speed">{formatSpeed(item.speed, t)}</span>
              )}
              {item.status === 'completed' && (
                <span className="task-speed">
                  {t('tasks.summary', { size: formatBytes(item.total_bytes, t), time: formatDuration(item.elapsed_ms, t) })}
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
      )}
      <>
      {hasRetryable && <FabButton icon={mdiRestart} ariaLabel={t('tasks.actions.retryAll')} disabled={retrying} style={{ bottom: 96 }} onClick={() => { void onRetryAll(); }} />}
      {hasCompleted && <FabButton icon={mdiBroom} ariaLabel={t('tasks.actions.clearCompleted')} disabled={clearing} onClick={() => { void onClearCompleted(); }} />}
      </>
    </div>
  );
}
