// src/components/BookCollectionPicker.tsx
import { useEffect, useState, useRef } from 'react';
import { useI18n } from '@/hooks/useI18n';
import { useCollectionsStore } from '@/stores/collections';
import { M3eDialog } from '@m3e/react/dialog';
import { M3eButton } from '@m3e/react/button';

interface BookCollectionPickerProps {
  bookId: string;
  onClose: () => void;
}

export function BookCollectionPicker({ bookId, onClose }: BookCollectionPickerProps) {
  const { t } = useI18n();
  const store = useCollectionsStore();
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const initialIds = useRef<Set<string>>(new Set());
  const [open, setOpen] = useState(!!bookId);

  useEffect(() => {
    void (async () => {
      store.ensureLoaded();
      const ids = await store.getBookCollections(bookId);
      setCheckedIds(new Set(ids));
      initialIds.current = new Set(ids);
    })();
  }, [bookId, store]);

  function toggle(collectionId: string) {
    setCheckedIds((prev) => {
      const next = new Set(prev);
      if (next.has(collectionId)) {
        next.delete(collectionId);
      } else {
        next.add(collectionId);
      }
      return next;
    });
  }

  async function handleClose() {
    const added: string[] = [];
    const removed: string[] = [];
    for (const id of checkedIds) {
      if (!initialIds.current.has(id)) added.push(id);
    }
    for (const id of initialIds.current) {
      if (!checkedIds.has(id)) removed.push(id);
    }
    await Promise.all([
      ...added.map((cid) => store.addBookToCollection(cid, bookId)),
      ...removed.map((cid) => store.removeBookFromCollection(cid, bookId)),
    ]);
    setOpen(false);
    onClose();
  }

  return (
    <M3eDialog open={open} onClosed={handleClose}>
      <div slot="headline">{t('lib.collections.addToTitle')}</div>
      <div slot="content" className="picker__content">
        {!store.collections.length ? (
          <div className="picker__empty">{t('lib.collections.empty')}</div>
        ) : (
          store.collections.map((col) => (
            <label key={col.id} className="picker__row">
              <input
                type="checkbox"
                className="picker__checkbox"
                checked={checkedIds.has(col.id)}
                onChange={() => toggle(col.id)}
              />
              <span className="picker__name">{col.name}</span>
            </label>
          ))
        )}
      </div>
      <div slot="actions">
        <M3eButton variant="filled" onClick={handleClose}>
          {t('common.confirm')}
        </M3eButton>
      </div>
    </M3eDialog>
  );
}

// src/components/BookCollectionPicker.vue
<template>
  <md-dialog
    ref="dialogRef"
    class="book-collection-picker"
    @close="onClose"
  >
    <div slot="headline">{{ t('lib.collections.addToTitle') }}</div>
    <div slot="content" class="picker__content">
      <div
        v-if="!store.collections.length"
        class="picker__empty"
      >
        {{ t('lib.collections.empty') }}
      </div>
      <label
        v-for="col in store.collections"
        :key="col.id"
        class="picker__row"
      >
        <input
          type="checkbox"
          class="picker__checkbox"
          :checked="checkedIds.has(col.id)"
          @change="toggle(col.id)"
        />
        <span class="picker__name">{{ col.name }}</span>
      </label>
    </div>
    <div slot="actions">
      <md-filled-button @click="close">{{ t('common.confirm') }}</md-filled-button>
    </div>
  </md-dialog>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useCollectionsStore } from '@/stores/collections';
import { useI18n } from '@/i18n';

const props = defineProps<{ bookId: string }>();
const emit = defineEmits<{ (e: 'close'): void }>();

const store = useCollectionsStore();
const { t } = useI18n();

const dialogRef = ref<{ show: () => void; close: () => void } | null>(null);
const checkedIds = ref<Set<string>>(new Set());
/** Snapshot of checked IDs at dialog open — used to compute deltas on close. */
const initialIds = ref<Set<string>>(new Set());

onMounted(async () => {
  store.ensureLoaded();
  const ids = await store.getBookCollections(props.bookId);
  checkedIds.value = new Set(ids);
  initialIds.value = new Set(ids);
  dialogRef.value?.show();
});

function toggle(collectionId: string) {
  const next = new Set(checkedIds.value);
  if (next.has(collectionId)) {
    next.delete(collectionId);
  } else {
    next.add(collectionId);
  }
  checkedIds.value = next;
}

async function onClose() {
  const added: string[] = [];
  const removed: string[] = [];
  for (const id of checkedIds.value) {
    if (!initialIds.value.has(id)) added.push(id);
  }
  for (const id of initialIds.value) {
    if (!checkedIds.value.has(id)) removed.push(id);
  }
  await Promise.all([
    ...added.map((cid) => store.addBookToCollection(cid, props.bookId)),
    ...removed.map((cid) => store.removeBookFromCollection(cid, props.bookId)),
  ]);
  emit('close');
}

function close() {
  dialogRef.value?.close();
}
</script>

<style scoped>
.book-collection-picker {
  --md-dialog-container-color: var(--md-sys-color-surface-container-high);
}

.picker__content {
  min-width: min(300px, 70vw);
  display: flex;
  flex-direction: column;
  gap: 4px;
  max-height: min(360px, 50vh);
  overflow-y: auto;
}

.picker__row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  border-radius: var(--md-sys-shape-corner-medium);
  cursor: pointer;
  transition: background-color 0.15s ease;
}

.picker__row:hover {
  background: color-mix(in srgb, var(--md-sys-color-on-surface) 8%, transparent);
}

.picker__checkbox {
  width: 18px;
  height: 18px;
  accent-color: var(--md-sys-color-primary);
  cursor: pointer;
  flex-shrink: 0;
}

.picker__name {
  font: var(--md-sys-typescale-body-large-weight)
    var(--md-sys-typescale-body-large-size) /
    var(--md-sys-typescale-body-large-line-height)
    var(--md-sys-typescale-font);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.picker__empty {
  padding: 16px;
  text-align: center;
  color: var(--md-sys-color-on-surface-variant);
  font: var(--md-sys-typescale-body-medium-weight)
    var(--md-sys-typescale-body-medium-size) /
    var(--md-sys-typescale-body-medium-line-height)
    var(--md-sys-typescale-font);
}
</style>
