// src/App.tsx
import { useEffect, useRef, useCallback, lazy, Suspense } from 'react';
import { HashRouter, Routes, Route, Navigate, useLocation } from 'react-router-dom';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { I18nProvider, onLocaleChange, getLocale } from '@/hooks/useI18n';
import { api } from '@/services/api';
import { useThemeStore } from '@/stores/theme';
import { useSettingsStore } from '@/stores/settings';
import { useLibraryStore } from '@/stores/library';
// Instantiate the browse stores at app start so their task://progress
// listeners are armed immediately — a download that finishes on any page
// flips the corresponding card in every source, not just a mounted view.
// (Module-level zustand stores initialize on import.)
import '@/stores/ehentai-browse';
import '@/stores/pixiv-browse';
import '@/stores/nicecat-browse';
import '@/stores/ahentai-browse';
import { AppShell } from '@/components/AppShell';
import { AppToast } from '@/components/AppToast';
import { ErrorBoundary } from '@/components/ErrorBoundary';

const Home = lazy(() => import('@/views/Home'));
const Library = lazy(() => import('@/views/Library'));
const Reader = lazy(() => import('@/views/Reader'));
const PixivDownload = lazy(() => import('@/views/PixivDownload'));
const EHentai = lazy(() => import('@/views/EHentai'));
const AHentai = lazy(() => import('@/views/AHentai'));
const NiceCat = lazy(() => import('@/views/NiceCat'));
const Tasks = lazy(() => import('@/views/Tasks'));
const Settings = lazy(() => import('@/views/Settings'));

function LoadingFallback() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 48 }}>
      <svg className="spinner" style={{ color: 'var(--md-sys-color-primary)' }} viewBox="0 0 50 50" aria-hidden="true">
        <circle className="spinner-track" cx="25" cy="25" r="20" />
        <circle className="spinner-arc" cx="25" cy="25" r="20" />
      </svg>
    </div>
  );
}

function isScrollPersistable(path: string) { return !path.startsWith('/reader'); }
function scrollKey(path: string) { return `erolib.scroll.${path}`; }

function AppContent() {
  const location = useLocation();
  const isReader = location.pathname.startsWith('/reader');
  const themeBgImage = useThemeStore((s) => s.themeBgImage);
  const mainRef = useRef<HTMLElement>(null);
  const saveScheduled = useRef(false);

  const scheduleSaveScroll = useCallback(() => {
    if (saveScheduled.current) return;
    saveScheduled.current = true;
    const path = location.pathname; // capture current path at call time
    requestAnimationFrame(() => {
      saveScheduled.current = false;
      const el = mainRef.current;
      if (!el || !isScrollPersistable(path)) return;
      try { localStorage.setItem(scrollKey(path), String(el.scrollTop)); } catch { /* ignore */ }
    });
  }, []); // no deps needed — we capture path at call time

  const restoreScroll = useCallback((path: string) => {
    const el = mainRef.current;
    if (!el || !isScrollPersistable(path)) return;
    let target: number;
    try { const raw = localStorage.getItem(scrollKey(path)); if (raw == null) return; target = Number(raw); } catch { return; }
    if (!Number.isFinite(target) || target <= 0) return;
    let attempt = 0;
    const trySet = () => {
      if (el.scrollHeight >= target) { el.scrollTop = target; return; }
      attempt++;
      if (attempt < 30) requestAnimationFrame(trySet);
      else el.scrollTop = target;
    };
    requestAnimationFrame(trySet);
  }, []);

  // Scrolling is persisted continuously by onScroll → scheduleSaveScroll (the
  // freshest outgoing value is already on disk by the time the route swaps).
  // Do NOT save here: by the time an effect runs, the new (shorter) route's
  // DOM has clamped scrollTop, and saving it would clobber the real position.
  useEffect(() => {
    const raf = requestAnimationFrame(() => restoreScroll(location.pathname));
    return () => cancelAnimationFrame(raf);
  }, [location.pathname, restoreScroll]);

  useEffect(() => {
    const onKeyDown = async (e: KeyboardEvent) => {
      if (e.key === 'F11') {
        e.preventDefault();
        try { const win = getCurrentWindow(); const isFs = await win.isFullscreen(); await win.setFullscreen(!isFs); } catch { /* ignore */ }
      }
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, []);

  useEffect(() => {
    void useSettingsStore.getState().autoStartAll();
    // Push the persisted locale to the backend on startup so SQL renders tags
    // in the right language from the first query (frontend localStorage is
    // the source of truth). Then, on locale change, refresh the library grid
    // + tag chips so every tag-bearing view re-renders in the new language.
    void api.setLocale(getLocale()).catch(() => {});
    const unsub = onLocaleChange(() => { void useLibraryStore.getState().refresh(); });
    return unsub;
  }, []);

  useEffect(() => {
    function handleMouseOver(e: MouseEvent) {
      const title = (e.target as HTMLElement).closest('.md3-card__title') as HTMLElement | null;
      if (!title || title.dataset.marqueeReady === '1') return;
      title.dataset.marqueeReady = '1';
      const inner = title.querySelector<HTMLElement>('.title-inner');
      if (!inner) return;
      const overflow = inner.scrollWidth - title.clientWidth;
      if (overflow <= 0) return;
      const rem = parseFloat(getComputedStyle(document.documentElement).fontSize) || 16;
      title.style.setProperty('--title-scroll', `${-overflow}px`);
      title.style.setProperty('--title-dur', `${overflow / (2 * rem) + 3}s`);
      title.classList.add('is-marquee');
    }
    document.addEventListener('mouseover', handleMouseOver);
    return () => document.removeEventListener('mouseover', handleMouseOver);
  }, []);

  return (
    <div id="erolib-app" className="erolib-app d-flex fill-height">
      {themeBgImage && !isReader && <div className="theme-bg-overlay" />}
      {!isReader && <AppShell />}
      <main ref={mainRef} className="app-main flex-grow-1" onScroll={scheduleSaveScroll}>
        <Suspense fallback={<LoadingFallback />}>
          <ErrorBoundary>
            <Routes>
            <Route path="/" element={<Navigate to="/home" replace />} />
            <Route path="/home" element={<Home />} />
            <Route path="/library" element={<Library />} />
            <Route path="/reader/:id" element={<Reader />} />
            <Route path="/pixiv" element={<PixivDownload />} />
            <Route path="/ehentai" element={<EHentai />} />
            <Route path="/ahentai" element={<AHentai />} />
            <Route path="/nicecat" element={<NiceCat />} />
            <Route path="/tasks" element={<Tasks />} />
            <Route path="/settings" element={<Settings />} />
            <Route path="*" element={
              <div className="text-center text-medium-emphasis mt-8" style={{ padding: 48 }}>
                <h2 className="text-h4">404</h2>
                <p className="text-body-1">Page not found</p>
              </div>
            } />
          </Routes>
          </ErrorBoundary>
        </Suspense>
      </main>
      <AppToast />
    </div>
  );
}

export function App() {
  return (
    <I18nProvider>
      <HashRouter>
        <AppContent />
      </HashRouter>
    </I18nProvider>
  );
}

// src/App.vue
<template>
  <div id="erolib-app" class="erolib-app d-flex fill-height">
    <div v-if="themeBgImage && !isReader" class="theme-bg-overlay" />
    <AppShell v-if="!isReader" />
    <main ref="appMainRef" class="app-main flex-grow-1">
      <router-view />
    </main>
    <AppToast />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, nextTick, watch } from 'vue';
import { useRoute } from 'vue-router';
import AppShell from './components/AppShell.vue';
import AppToast from './components/AppToast.vue';
import { useSettingsStore } from './stores/settings';
import { useThemeStore } from './stores/theme';
import { useLibraryStore } from './stores/library';
import { usePixivBrowseStore } from './stores/pixiv-browse';
import { useEhentaiBrowseStore } from './stores/ehentai-browse';
import { useNicecatBrowseStore } from './stores/nicecat-browse';
import { api } from './services/api';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { onLocaleChange, useI18n } from './i18n';

const route = useRoute();
const isReader = computed(() => route.path.startsWith('/reader'));
const themeStore = useThemeStore();
const themeBgImage = computed(() => themeStore.themeBgImage);
const settingsStore = useSettingsStore();
const { locale } = useI18n();

// Scroll container — every secondary view scrolls inside this <main>.
const appMainRef = ref<HTMLElement | null>(null);

const isScrollPersistable = (path: string) => !path.startsWith('/reader');
const scrollKey = (path: string) => `erolib.scroll.${path}`;

// --- Save scrollTop (rAF-throttled so we don't write on every scroll event) ---
let saveScheduled = false;
function scheduleSaveScroll() {
  if (saveScheduled) return;
  saveScheduled = true;
  requestAnimationFrame(() => {
    saveScheduled = false;
    const el = appMainRef.value;
    const path = route.path;
    if (!el || !isScrollPersistable(path)) return;
    try {
      localStorage.setItem(scrollKey(path), String(el.scrollTop));
    } catch {
      // ignore quota / privacy-mode errors
    }
  });
}

// --- Restore scrollTop, retrying a few frames until content is tall enough ---
const MAX_RESTORE_FRAMES = 30;
function restoreScroll(path: string) {
  const el = appMainRef.value;
  if (!el || !isScrollPersistable(path)) return;

  let target: number;
  try {
    const raw = localStorage.getItem(scrollKey(path));
    if (raw == null) return;
    target = Number(raw);
  } catch {
    return;
  }
  if (!Number.isFinite(target) || target <= 0) return;

  let attempt = 0;
  const trySet = () => {
    if (el.scrollHeight >= target) {
      el.scrollTop = target;
      return;
    }
    attempt += 1;
    if (attempt < MAX_RESTORE_FRAMES) {
      requestAnimationFrame(trySet);
    } else {
      // Gave up waiting for async content; land as far down as possible.
      el.scrollTop = target;
    }
  };
  requestAnimationFrame(trySet);
}

function onMainScroll() {
  scheduleSaveScroll();
}

// On navigation: save the old path, then restore the new one after layout.
watch(
  () => route.path,
  (path, oldPath) => {
    const el = appMainRef.value;
    if (el && oldPath && isScrollPersistable(oldPath)) {
      try {
        localStorage.setItem(scrollKey(oldPath), String(el.scrollTop));
      } catch {
        // ignore
      }
    }
    // nextTick + rAF: wait for the view swap + layout to settle.
    nextTick(() => {
      requestAnimationFrame(() => restoreScroll(path));
    });
  },
);

// F11 toggles fullscreen on any page (requires window focus, which is the
// browser's default expectation for programmatic fullscreen).
async function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'F11') {
    e.preventDefault();
    const win = getCurrentWindow();
    try {
      const isFs = await win.isFullscreen();
      await win.setFullscreen(!isFs);
    } catch {
      // ignore — e.g. permission not granted at runtime
    }
  }
}

onMounted(() => {
  const el = appMainRef.value;
  if (el) {
    el.addEventListener('scroll', onMainScroll, { passive: true });
  }
  window.addEventListener('keydown', onKeyDown);
  // Restore the initial view's scroll after first layout.
  nextTick(() => {
    requestAnimationFrame(() => restoreScroll(route.path));
  });
  // Auto-start the OPDS/RSS sharing servers so they're running the moment the
  // app opens (saved ports — single source of truth).
  void settingsStore.autoStartAll();

  // Instantiate browse stores at app start so their task://progress listeners
  // are armed immediately — a download that finishes while the user is on the
  // Tasks page (or anywhere else) flips the corresponding card in any source,
  // not just the one whose view happens to be mounted. Pinia returns the same
  // singleton on later useXxxBrowseStore() calls, so each listener registers
  // exactly once per source.
  usePixivBrowseStore();
  useEhentaiBrowseStore();
  useNicecatBrowseStore();

  // Push the current locale to the backend on startup so SQL renders tags in
  // the right language from the first query (the backend `settings` row is
  // empty until pushed; the frontend's localStorage value is the source of
  // truth). Then, whenever the locale changes, refresh the library grid + tag
  // chips + metadata so every tag-bearing view re-renders in the new language.
  void api.setLocale(locale.value).catch(() => {});
  onLocaleChange(() => {
    void useLibraryStore().refresh();
  });
});

onBeforeUnmount(() => {
  const el = appMainRef.value;
  if (el) {
    el.removeEventListener('scroll', onMainScroll);
  }
  window.removeEventListener('keydown', onKeyDown);
});
</script>

<style>
.erolib-app {
  min-height: 100vh;
  background: var(--md-sys-color-surface);
}

.app-main {
  display: flex;
  flex-direction: column;
  overflow: auto;
}

/* Custom-theme background overlay — bottom-right image fading toward top-left.
   Only shown on non-reader pages; the reader already forces its own dark theme
   and would clash with a semi-transparent overlay. */
.theme-bg-overlay {
  position: fixed;
  inset: 0;
  z-index: 0;
  pointer-events: none;
  background-image: var(--theme-bg-image);
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  mask-image: linear-gradient(to top, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.02) 80%);
  -webkit-mask-image: linear-gradient(to top, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.02) 80%);
}
</style>
